### ISSUE TITLE
dialyxir through error

### ISSUE THREAD

**Issue by houmanka** [aaronrenner/zone-meal-tracker#2]
I downloaded your application then I ran `mix deps.get` and then I did `mix phx.server`. I am getting 
```
== Compilation error in file lib/dialyxir/project.ex ==
** (CompileError) lib/dialyxir/project.ex:3: cannot import Dialyxir.Output.info/1 because it is undefined or private
    (elixir) src/elixir_import.erl:78: :elixir_import.calculate/6
    (elixir) src/elixir_import.erl:18: :elixir_import.import/4
could not compile dependency :dialyxir, "mix compile" failed. You can recompile this dependency with "mix deps.compile dialyxir", update it with "mix deps.update dialyxir" or clean it with "mix deps.clean dialyxir"
```

So I did update my dialyxir and ran the phx again. Same error.

Do you know why?

**Comment by aaronrenner** [comment]
@houmanka Thanks for reading the blog post and checking out my app. ❤️ 

Unfortunately, I'm unable to recreate the issue locally. It might be worth seeing if you could install dialyxir in a separate project and see if it compiles there. If it's helpful at all, you can see the versions of Elixir/OTP I'm running in the `.tool-versions` file: https://github.com/aaronrenner/zone-meal-tracker/blob/d2f48e14e21ac341be4b1540c9cd2fa76060f900/.tool-versions.

Another option would be to comment out the `dialyzer` dependency in the `mix.exs` file and start the app without it. This project is more of a playground for me and currently only has the authentication code that I mentioned in the blog post.

**Comment by houmanka** [comment]
Hi, Thank you for your response. I want to explore the way you coded and how your code organisations and test. I want to find the reasoning and thoughts behind the way you coded. 

I have been working on 2 good size Elixir project for about 2 years now. one is the core of the business and the other one is kind of complementary of the first application.
They are for Mining industry.
I have commented the `dialyzer` out. All good now.

Thanks again.

**Comment by aaronrenner** [comment]
That's great you got it working by commenting out dialyxir. I just upgraded `dialylxir` in this commit: https://github.com/aaronrenner/zone-meal-tracker/commit/e8af4dcbeb8907f3927d374ffeff617551c8eee0, which might help. I did run `mix do deps.clean --all, deps.get` after the upgrade because I was getting some different dialyixir errors.

Feel free to reach out with any questions about why I wrote things the way I did. I'm also continuing to play with the app, so there will be more code and functionality over the coming months.
